// tests/lint_busywork_integration.rs
//
// Integration tests for `uws lint busywork` — verifies the AntiBusyworkFactor
// (ABF) ruleset fires correctly on synthetic fixtures.
//
// These tests run against the public API of the `lint_busywork` module and do
// NOT require a network connection or git repository.

use uws::lint_busywork::{
    default_rules, scan, ScanInput, Severity,
};

// ─── Fixture helpers ──────────────────────────────────────────────────────────

fn make_input(
    commits: Vec<&str>,
    files: Vec<&str>,
    diff: Vec<&str>,
) -> ScanInput {
    ScanInput {
        commit_messages: commits.into_iter().map(|s| s.to_string()).collect(),
        changed_files: files.into_iter().map(|s| s.to_string()).collect(),
        diff_lines: diff.into_iter().map(|s| s.to_string()).collect(),
    }
}

// ─── ABF-001: Pure version-bump commit message ────────────────────────────────

#[test]
fn abf001_fires_on_semver_only_commit() {
    let input = make_input(vec!["1.2.3"], vec![], vec![]);
    let findings = scan(&input, &default_rules());
    assert!(
        findings.iter().any(|f| f.rule_id == "ABF-001"),
        "ABF-001 must fire on standalone semver commit message '1.2.3'"
    );
}

#[test]
fn abf001_fires_on_bump_version_phrasing() {
    let messages = vec![
        "bump version to 2.0.0",
        "chore: bump version",
        "chore(release): 3.1.4",
        "prepare release 1.0.0",
    ];
    for msg in messages {
        let input = make_input(vec![msg], vec![], vec![]);
        let findings = scan(&input, &default_rules());
        assert!(
            findings.iter().any(|f| f.rule_id == "ABF-001"),
            "ABF-001 must fire on: {msg:?}"
        );
    }
}

#[test]
fn abf001_silent_on_meaningful_commits() {
    let good_messages = vec![
        "feat: add GoldenTrace provenance trailer",
        "fix: handle empty diff in busywork scanner",
        "docs: update README with swarm review examples",
        "refactor: extract scan_input builder from handle_busywork",
    ];
    for msg in good_messages {
        let input = make_input(vec![msg], vec![], vec![]);
        let findings = scan(&input, &default_rules());
        assert!(
            !findings.iter().any(|f| f.rule_id == "ABF-001"),
            "ABF-001 must NOT fire on meaningful commit: {msg:?}"
        );
    }
}

// ─── ABF-002: Large whitespace-only PR ───────────────────────────────────────

#[test]
fn abf002_fires_on_51_files_all_whitespace_diff() {
    // 51 changed files; diff is 100% whitespace-only changed lines
    let files: Vec<&str> = (0..51).map(|_| "src/file.rs").collect();
    let diff: Vec<&str> = (0..200).map(|_| "+   ").collect(); // all whitespace additions
    let input = make_input(vec![], files, diff);
    let findings = scan(&input, &default_rules());
    assert!(
        findings.iter().any(|f| f.rule_id == "ABF-002"),
        "ABF-002 must fire when >50 files and ≥90% whitespace diff"
    );
}

#[test]
fn abf002_silent_on_50_files_threshold() {
    // Exactly 50 files — should not fire (threshold is >50)
    let files: Vec<&str> = (0..50).map(|_| "src/file.rs").collect();
    let diff: Vec<&str> = (0..200).map(|_| "+   ").collect();
    let input = make_input(vec![], files, diff);
    let findings = scan(&input, &default_rules());
    assert!(
        !findings.iter().any(|f| f.rule_id == "ABF-002"),
        "ABF-002 must NOT fire when exactly 50 files changed"
    );
}

// ─── ABF-004: Changelog-only PR ──────────────────────────────────────────────

#[test]
fn abf004_fires_on_changelog_only_pr() {
    let input = make_input(
        vec![],
        vec!["CHANGELOG.md", "CHANGES.md"],
        vec![],
    );
    let findings = scan(&input, &default_rules());
    assert!(
        findings.iter().any(|f| f.rule_id == "ABF-004"),
        "ABF-004 must fire when all changed files are changelogs"
    );
}

// ─── ABF-005: Auto-generated noise ───────────────────────────────────────────

#[test]
fn abf005_fires_on_autogenerated_commit() {
    let input = make_input(vec!["auto-update generated files"], vec![], vec![]);
    let findings = scan(&input, &default_rules());
    assert!(
        findings.iter().any(|f| f.rule_id == "ABF-005"),
        "ABF-005 must fire on auto-generated commit"
    );
}

// ─── Full default ruleset ────────────────────────────────────────────────────

#[test]
fn default_ruleset_has_five_rules() {
    let rules = default_rules();
    assert_eq!(rules.len(), 5, "v0 ruleset must have exactly 5 rules");
    let ids: Vec<&str> = rules.iter().map(|r| r.id()).collect();
    assert!(ids.contains(&"ABF-001"));
    assert!(ids.contains(&"ABF-002"));
    assert!(ids.contains(&"ABF-003"));
    assert!(ids.contains(&"ABF-004"));
    assert!(ids.contains(&"ABF-005"));
}

#[test]
fn clean_repo_produces_no_findings() {
    // No suspicious commits, small PR, real code changes
    let input = make_input(
        vec![
            "feat: implement swarm review CLI stub",
            "feat: add GoldenTrace provenance trailer",
        ],
        vec!["src/swarm.rs", "src/golden_trace.rs", "src/main.rs"],
        vec![
            "+ pub fn handle_review() {",
            "+     println!(\"stub\");",
            "+ }",
        ],
    );
    let findings = scan(&input, &default_rules());
    assert!(
        findings.is_empty(),
        "Clean synthetic repo should produce zero findings, got: {findings:?}"
    );
}

#[test]
fn severity_values_are_valid() {
    // Verify Severity::as_str returns the expected strings
    assert_eq!(Severity::Warning.as_str(), "warning");
    assert_eq!(Severity::Error.as_str(), "error");
    assert_eq!(Severity::Info.as_str(), "info");
}
