// src/telemetry/linter.rs
// Aluminum OS — Systemic Busywork Linter (V1)
//
// A static analysis pass that scans source-file text for known "extractive"
// or "busywork" anti-patterns and flags them as NPFM-lowering warnings.
//
// Anti-patterns detected:
//   1. Deeply nested generic boilerplate (e.g. `Vec<Vec<Vec<`)
//   2. Redundant no-op wrapper functions (`fn x() { y() }`)
//   3. TODO/FIXME comments left in production code
//   4. Highly duplicated consecutive blank lines (≥ 4 in a row)
//   5. Auto-generated boilerplate markers
//   6. Trivial re-export wrappers (`pub use … as …;` without docs)
//
// Each pattern returns a `LintWarning`. The public entry point is:
//
//   `scan_for_busywork(file_contents: &str) -> Result<(), String>`
//
// Returns `Ok(())` when no busywork is detected, or `Err(summary)` listing
// all warnings if busywork patterns are found.
//
// Author: GitHub Copilot — Council Session 2026-03-21
// Invariants: INV-1 (Anti-Busywork), INV-3 (Audit Trail)

#![allow(dead_code)]

// ─── Warning Types ─────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BusyworkKind {
    /// Generic type nesting depth > 2 (e.g. `Vec<Vec<Vec<T>>>`)
    DeeplyNestedGenerics,
    /// Function body is a single call of another function with no transformation
    RedundantWrapper,
    /// TODO or FIXME comment left in production code
    TodoComment,
    /// Four or more consecutive blank lines
    ExcessiveBlankLines,
    /// Auto-generated file marker
    AutoGeneratedMarker,
    /// `pub use X as Y` re-export without any documentation comment
    UndocumentedReExport,
}

impl std::fmt::Display for BusyworkKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BusyworkKind::DeeplyNestedGenerics => write!(f, "DeeplyNestedGenerics"),
            BusyworkKind::RedundantWrapper => write!(f, "RedundantWrapper"),
            BusyworkKind::TodoComment => write!(f, "TodoComment"),
            BusyworkKind::ExcessiveBlankLines => write!(f, "ExcessiveBlankLines"),
            BusyworkKind::AutoGeneratedMarker => write!(f, "AutoGeneratedMarker"),
            BusyworkKind::UndocumentedReExport => write!(f, "UndocumentedReExport"),
        }
    }
}

/// A single detected busywork pattern.
#[derive(Debug, Clone)]
pub struct LintWarning {
    /// Zero-based line number where the pattern was detected
    pub line: usize,
    /// Category of busywork
    pub kind: BusyworkKind,
    /// Human-readable description
    pub message: String,
}

// ─── Scan Entry Point ──────────────────────────────────────────

/// Scan `file_contents` for known busywork anti-patterns.
///
/// Returns `Ok(())` when the file is clean.
/// Returns `Err(summary)` with a multi-line warning listing when issues are
/// found, allowing the caller to surface them as NPFM score degradations.
pub fn scan_for_busywork(file_contents: &str) -> Result<(), String> {
    let warnings = collect_warnings(file_contents);
    if warnings.is_empty() {
        return Ok(());
    }

    let summary = warnings
        .iter()
        .map(|w| format!("  line {}: [{}] {}", w.line + 1, w.kind, w.message))
        .collect::<Vec<_>>()
        .join("\n");

    Err(format!(
        "NPFM score degradation: {} busywork pattern(s) detected\n{}",
        warnings.len(),
        summary
    ))
}

/// Return all `LintWarning`s found in `file_contents`.
pub fn collect_warnings(file_contents: &str) -> Vec<LintWarning> {
    let mut warnings: Vec<LintWarning> = Vec::new();
    let lines: Vec<&str> = file_contents.lines().collect();

    check_deeply_nested_generics(&lines, &mut warnings);
    check_redundant_wrappers(&lines, &mut warnings);
    check_todo_comments(&lines, &mut warnings);
    check_excessive_blank_lines(&lines, &mut warnings);
    check_auto_generated_markers(&lines, &mut warnings);
    check_undocumented_reexports(&lines, &mut warnings);

    warnings
}

// ─── Individual Checkers ───────────────────────────────────────

/// Detect generic nesting depth > 2 on a single line (e.g. `Vec<Vec<Vec<`).
fn check_deeply_nested_generics(lines: &[&str], warnings: &mut Vec<LintWarning>) {
    for (i, line) in lines.iter().enumerate() {
        let depth = count_open_angle_bracket_depth(line);
        if depth >= 3 {
            warnings.push(LintWarning {
                line: i,
                kind: BusyworkKind::DeeplyNestedGenerics,
                message: format!(
                    "Generic nesting depth {} detected — consider a type alias to reduce boilerplate",
                    depth
                ),
            });
        }
    }
}

/// Count the maximum depth of `<` nesting on a single line (heuristic).
fn count_open_angle_bracket_depth(line: &str) -> usize {
    let mut depth: usize = 0;
    let mut max_depth: usize = 0;
    let mut in_string = false;
    let mut prev = ' ';
    for ch in line.chars() {
        if ch == '"' && prev != '\\' {
            in_string = !in_string;
        }
        if !in_string {
            if ch == '<' {
                depth += 1;
                if depth > max_depth {
                    max_depth = depth;
                }
            } else if ch == '>' {
                depth = depth.saturating_sub(1);
            }
        }
        prev = ch;
    }
    max_depth
}

/// Detect functions whose body is a single call site forwarding all arguments
/// (heuristic: single-line body `{ other_fn(` pattern).
fn check_redundant_wrappers(lines: &[&str], warnings: &mut Vec<LintWarning>) {
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i].trim();

        // Match `fn name(...) {` on one line with the body on the next line
        if (line.starts_with("fn ") || line.starts_with("pub fn "))
            && line.ends_with('{')
            && !line.contains("->")
        {
            // Look at the next non-blank line
            if let Some((body_idx, body)) = lines
                .iter()
                .enumerate()
                .skip(i + 1)
                .find(|(_, l)| !l.trim().is_empty())
            {
                let body_trimmed = body.trim();
                // Single-call body: just `ident(` optionally ending with `)`
                if body_trimmed.ends_with(");")
                    && !body_trimmed.starts_with("//")
                    && !body_trimmed.contains("if ")
                    && !body_trimmed.contains("let ")
                {
                    // Check the line after that is `}`
                    if let Some((_, close)) = lines
                        .iter()
                        .enumerate()
                        .skip(body_idx + 1)
                        .find(|(_, l)| !l.trim().is_empty())
                    {
                        if close.trim() == "}" {
                            warnings.push(LintWarning {
                                line: i,
                                kind: BusyworkKind::RedundantWrapper,
                                message: "Function appears to be a no-op wrapper \
                                          with no transformation — consider inlining or removing"
                                    .to_string(),
                            });
                        }
                    }
                }
            }
        }
        i += 1;
    }
}

/// Detect `// TODO` or `// FIXME` comments.
fn check_todo_comments(lines: &[&str], warnings: &mut Vec<LintWarning>) {
    for (i, line) in lines.iter().enumerate() {
        let trimmed = line.trim();
        let lower = trimmed.to_lowercase();
        if (lower.contains("// todo") || lower.contains("// fixme"))
            && !lower.contains("// todo: replace")
        {
            warnings.push(LintWarning {
                line: i,
                kind: BusyworkKind::TodoComment,
                message: "TODO/FIXME comment in production code — resolve or track in issue tracker"
                    .to_string(),
            });
        }
    }
}

/// Detect four or more consecutive blank lines.
fn check_excessive_blank_lines(lines: &[&str], warnings: &mut Vec<LintWarning>) {
    let mut consecutive: usize = 0;
    let mut reported = false;
    for (i, line) in lines.iter().enumerate() {
        if line.trim().is_empty() {
            consecutive += 1;
            if consecutive >= 4 && !reported {
                warnings.push(LintWarning {
                    line: i,
                    kind: BusyworkKind::ExcessiveBlankLines,
                    message: format!(
                        "{} consecutive blank lines — reduce to improve readability",
                        consecutive
                    ),
                });
                reported = true;
            }
        } else {
            consecutive = 0;
            reported = false;
        }
    }
}

/// Detect common auto-generated file markers.
fn check_auto_generated_markers(lines: &[&str], warnings: &mut Vec<LintWarning>) {
    let markers = [
        "auto-generated",
        "autogenerated",
        "do not edit",
        "do not modify",
        "generated by",
        "@generated",
    ];
    for (i, line) in lines.iter().enumerate() {
        let lower = line.to_lowercase();
        if markers.iter().any(|m| lower.contains(m)) {
            warnings.push(LintWarning {
                line: i,
                kind: BusyworkKind::AutoGeneratedMarker,
                message:
                    "Auto-generated marker detected — generated code raises NPFM busywork flag"
                        .to_string(),
            });
        }
    }
}

/// Detect `pub use X as Y;` lines that are not preceded by a doc comment.
fn check_undocumented_reexports(lines: &[&str], warnings: &mut Vec<LintWarning>) {
    for (i, line) in lines.iter().enumerate() {
        let trimmed = line.trim();
        if trimmed.starts_with("pub use ") && trimmed.contains(" as ") && trimmed.ends_with(';') {
            let has_doc = i > 0 && lines[i - 1].trim().starts_with("///");
            if !has_doc {
                warnings.push(LintWarning {
                    line: i,
                    kind: BusyworkKind::UndocumentedReExport,
                    message: "Re-export alias without doc comment — add `///` to explain why"
                        .to_string(),
                });
            }
        }
    }
}

// ─── Tests ─────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── scan_for_busywork ─────────────────────────────

    #[test]
    fn test_clean_file_returns_ok() {
        let code = r#"
fn add(a: i32, b: i32) -> i32 {
    a + b
}
"#;
        assert!(scan_for_busywork(code).is_ok());
    }

    #[test]
    fn test_busywork_file_returns_err() {
        let code = "// TODO: fix this later\n";
        assert!(scan_for_busywork(code).is_err());
    }

    #[test]
    fn test_err_message_contains_line_number() {
        let code = "// TODO: something\n";
        let err = scan_for_busywork(code).unwrap_err();
        assert!(err.contains("line 1:"));
    }

    // ── DeeplyNestedGenerics ──────────────────────────

    #[test]
    fn test_detects_triple_nested_generic() {
        let code = "type Foo = Vec<Vec<Vec<u8>>>;";
        let warnings = collect_warnings(code);
        assert!(warnings.iter().any(|w| w.kind == BusyworkKind::DeeplyNestedGenerics));
    }

    #[test]
    fn test_allows_double_nested_generic() {
        let code = "type Foo = Vec<Vec<u8>>;";
        let warnings = collect_warnings(code);
        assert!(!warnings.iter().any(|w| w.kind == BusyworkKind::DeeplyNestedGenerics));
    }

    // ── RedundantWrapper ──────────────────────────────

    #[test]
    fn test_detects_redundant_wrapper() {
        let code = "pub fn wrapper() {\n    other_call();\n}\n";
        let warnings = collect_warnings(code);
        assert!(warnings.iter().any(|w| w.kind == BusyworkKind::RedundantWrapper));
    }

    #[test]
    fn test_real_function_not_flagged() {
        let code = "pub fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n";
        let warnings = collect_warnings(code);
        assert!(!warnings.iter().any(|w| w.kind == BusyworkKind::RedundantWrapper));
    }

    // ── TodoComment ───────────────────────────────────

    #[test]
    fn test_detects_todo_comment() {
        let code = "// TODO: fix this\n";
        let warnings = collect_warnings(code);
        assert!(warnings.iter().any(|w| w.kind == BusyworkKind::TodoComment));
    }

    #[test]
    fn test_detects_fixme_comment() {
        let code = "// FIXME: broken\n";
        let warnings = collect_warnings(code);
        assert!(warnings.iter().any(|w| w.kind == BusyworkKind::TodoComment));
    }

    #[test]
    fn test_normal_comment_not_flagged() {
        let code = "// This function handles errors\n";
        let warnings = collect_warnings(code);
        assert!(!warnings.iter().any(|w| w.kind == BusyworkKind::TodoComment));
    }

    // ── ExcessiveBlankLines ───────────────────────────

    #[test]
    fn test_detects_four_blank_lines() {
        let code = "fn a() {}\n\n\n\n\nfn b() {}\n";
        let warnings = collect_warnings(code);
        assert!(warnings.iter().any(|w| w.kind == BusyworkKind::ExcessiveBlankLines));
    }

    #[test]
    fn test_three_blank_lines_ok() {
        let code = "fn a() {}\n\n\n\nfn b() {}\n";
        let warnings = collect_warnings(code);
        assert!(!warnings.iter().any(|w| w.kind == BusyworkKind::ExcessiveBlankLines));
    }

    // ── AutoGeneratedMarker ───────────────────────────

    #[test]
    fn test_detects_do_not_edit() {
        let code = "// DO NOT EDIT — generated by protoc\n";
        let warnings = collect_warnings(code);
        assert!(warnings.iter().any(|w| w.kind == BusyworkKind::AutoGeneratedMarker));
    }

    #[test]
    fn test_detects_at_generated() {
        let code = "// @generated\n";
        let warnings = collect_warnings(code);
        assert!(warnings.iter().any(|w| w.kind == BusyworkKind::AutoGeneratedMarker));
    }

    // ── UndocumentedReExport ──────────────────────────

    #[test]
    fn test_detects_undocumented_reexport() {
        let code = "pub use foo::Bar as MyBar;\n";
        let warnings = collect_warnings(code);
        assert!(warnings.iter().any(|w| w.kind == BusyworkKind::UndocumentedReExport));
    }

    #[test]
    fn test_documented_reexport_passes() {
        let code = "/// Re-export for ergonomics\npub use foo::Bar as MyBar;\n";
        let warnings = collect_warnings(code);
        assert!(!warnings.iter().any(|w| w.kind == BusyworkKind::UndocumentedReExport));
    }

    // ── count_open_angle_bracket_depth ───────────────

    #[test]
    fn test_angle_bracket_depth_zero() {
        assert_eq!(count_open_angle_bracket_depth("let x = 1;"), 0);
    }

    #[test]
    fn test_angle_bracket_depth_one() {
        assert_eq!(count_open_angle_bracket_depth("Vec<u8>"), 1);
    }

    #[test]
    fn test_angle_bracket_depth_three() {
        assert_eq!(count_open_angle_bracket_depth("Vec<Vec<Vec<u8>>>"), 3);
    }
}
