// src/ledger/provenance.rs
// Regenerative IP & Provenance Engine
//
// Provides cryptographic IP tracking for code generation.
// Every commit that passes a HITL review can be signed with a
// ProvenanceTrailer that permanently records human vs. AI contribution
// percentages, a revenue-split policy, and the reviewer's HITL signature.
//
// CLI surface:
//   uws ip sign     — append a ProvenanceTrailer to the current HEAD commit
//   uws ip monetize — register the IP with the decentralised payout ledger
//
// Design principles:
//   • Human contribution is never zero — HITL review IS economic value.
//   • All fields are serialised as deterministic JSON before signing.
//   • The signature is a portable FNV-1a 256-bit hash (same algorithm as
//     audit_chain) so no external crates are required.  A production
//     deployment SHOULD replace this with ML-DSA / Ed25519.

#![allow(dead_code)]

use std::fmt;
use std::time::{SystemTime, UNIX_EPOCH};

// ─── Constants ────────────────────────────────────────────────────────────────

/// Minimum allowed human contribution weight (0.0 – 1.0).
/// Enforces the principle that a pure AI commit without HITL review
/// cannot receive a provenance trailer.
pub const MIN_HUMAN_WEIGHT: f64 = 0.01;

/// Maximum allowed AI contribution weight (0.0 – 1.0).
pub const MAX_AI_WEIGHT: f64 = 0.99;

// ─── Core Structures ──────────────────────────────────────────────────────────

/// Records the economic and scientific attribution for a single IP asset
/// (typically a git commit).  Intended to be serialised into a git note or
/// commit trailer so the attribution is permanently embedded in the repo.
#[derive(Debug, Clone)]
pub struct ProvenanceTrailer {
    /// Schema version for forward-compatibility.
    pub schema_version: String,
    /// ISO 8601 UTC timestamp when the trailer was created.
    pub timestamp: String,
    /// The git commit SHA this trailer is attached to.
    pub commit_sha: String,
    /// Free-text description of the IP asset.
    pub description: String,
    /// Fraction of value attributed to human HITL work (0.0 – 1.0).
    pub human_weight: f64,
    /// Fraction of value attributed to AI generation (0.0 – 1.0).
    pub ai_weight: f64,
    /// Revenue distribution policy for this asset.
    pub revenue_split: RevenueSplit,
    /// HITL reviewer signature proving human oversight.
    pub hitl_signature: HitlSignature,
}

/// Defines how downstream revenue generated by this IP should be distributed.
#[derive(Debug, Clone)]
pub struct RevenueSplit {
    /// Wallet / identifier of the primary human creator.
    pub creator_id: String,
    /// Percentage of revenue routed to the creator (0 – 100).
    pub creator_pct: u8,
    /// Name of the payout ledger (e.g. "krakoa-free-bank", "github-sponsors").
    pub ledger: String,
    /// Optional secondary beneficiaries (id → percentage).
    pub secondary: Vec<(String, u8)>,
}

/// Cryptographic proof that a human reviewed and approved the IP asset.
#[derive(Debug, Clone)]
pub struct HitlSignature {
    /// Human reviewer identifier (GitHub username, DID, or key fingerprint).
    pub reviewer_id: String,
    /// Hex-encoded signature of the canonical provenance payload.
    pub signature_hex: String,
    /// Algorithm used (e.g. "FNV1a-256-portable", "Ed25519", "ML-DSA").
    pub algorithm: String,
}

// ─── Provenance Trailer ───────────────────────────────────────────────────────

impl ProvenanceTrailer {
    /// Build a new `ProvenanceTrailer`.
    ///
    /// Validates that `human_weight` and `ai_weight` are in range and sum to 1.0,
    /// then captures the current UTC timestamp, generates a cryptographic signature
    /// over the canonical payload (see [`portable_sign`] for algorithm details),
    /// and returns the fully-constructed trailer ready for serialisation.
    ///
    /// # Errors
    /// Returns an error string if weights are out of range or do not sum to ≤ 1.0.
    pub fn new(
        commit_sha: impl Into<String>,
        description: impl Into<String>,
        human_weight: f64,
        ai_weight: f64,
        creator_id: impl Into<String>,
        creator_pct: u8,
        ledger: impl Into<String>,
        reviewer_id: impl Into<String>,
    ) -> Result<Self, String> {
        let human_weight = (human_weight * 100.0).round() / 100.0;
        let ai_weight = (ai_weight * 100.0).round() / 100.0;

        if human_weight < MIN_HUMAN_WEIGHT {
            return Err(format!(
                "human_weight must be ≥ {MIN_HUMAN_WEIGHT} (HITL review is required)"
            ));
        }
        if ai_weight > MAX_AI_WEIGHT {
            return Err(format!(
                "ai_weight must be ≤ {MAX_AI_WEIGHT}"
            ));
        }
        if (human_weight + ai_weight - 1.0).abs() > 0.01 {
            return Err(format!(
                "human_weight ({human_weight}) + ai_weight ({ai_weight}) must equal 1.0"
            ));
        }

        let revenue_split = RevenueSplit {
            creator_id: creator_id.into(),
            creator_pct,
            ledger: ledger.into(),
            secondary: vec![],
        };

        // Build a deterministic canonical payload and sign it.
        let reviewer_id: String = reviewer_id.into();
        let commit_sha: String = commit_sha.into();
        let description: String = description.into();
        let timestamp = current_timestamp();

        let canonical = canonical_payload(
            &commit_sha,
            &description,
            human_weight,
            ai_weight,
            &revenue_split,
            &reviewer_id,
            &timestamp,
        );
        let signature_hex = portable_sign(&canonical);

        let hitl_signature = HitlSignature {
            reviewer_id,
            signature_hex,
            algorithm: "FNV1a-256-portable".to_string(),
        };

        Ok(ProvenanceTrailer {
            schema_version: "1.0.0".to_string(),
            timestamp,
            commit_sha,
            description,
            human_weight,
            ai_weight,
            revenue_split,
            hitl_signature,
        })
    }

    /// Serialise the trailer to a compact JSON string suitable for embedding
    /// in a git commit trailer or note.
    ///
    /// NOTE: The description field is escaped for safe JSON embedding (backslash,
    /// double-quote, and control characters are all escaped).
    pub fn to_json(&self) -> String {
        let secondary_json: String = self
            .revenue_split
            .secondary
            .iter()
            .map(|(id, pct)| format!("{{\"id\":{},\"pct\":{pct}}}", json_escape(id)))
            .collect::<Vec<_>>()
            .join(",");

        format!(
            concat!(
                "{{",
                "\"schema_version\":\"{sv}\",",
                "\"timestamp\":\"{ts}\",",
                "\"commit_sha\":\"{sha}\",",
                "\"description\":{desc},",
                "\"human_weight\":{hw},",
                "\"ai_weight\":{aw},",
                "\"revenue_split\":{{",
                "\"creator_id\":\"{cid}\",",
                "\"creator_pct\":{cpct},",
                "\"ledger\":\"{ledger}\",",
                "\"secondary\":[{sec}]",
                "}},",
                "\"hitl_signature\":{{",
                "\"reviewer_id\":\"{rid}\",",
                "\"signature_hex\":\"{sig}\",",
                "\"algorithm\":\"{alg}\"",
                "}}",
                "}}"
            ),
            sv = self.schema_version,
            ts = self.timestamp,
            sha = self.commit_sha,
            desc = json_escape(&self.description),
            hw = self.human_weight,
            aw = self.ai_weight,
            cid = self.revenue_split.creator_id,
            cpct = self.revenue_split.creator_pct,
            ledger = self.revenue_split.ledger,
            sec = secondary_json,
            rid = self.hitl_signature.reviewer_id,
            sig = self.hitl_signature.signature_hex,
            alg = self.hitl_signature.algorithm,
        )
    }

    /// Verify that the embedded HITL signature matches the trailer's payload.
    pub fn verify(&self) -> bool {
        let canonical = canonical_payload(
            &self.commit_sha,
            &self.description,
            self.human_weight,
            self.ai_weight,
            &self.revenue_split,
            &self.hitl_signature.reviewer_id,
            &self.timestamp,
        );
        let expected = portable_sign(&canonical);
        expected == self.hitl_signature.signature_hex
    }
}

impl fmt::Display for ProvenanceTrailer {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "ProvenanceTrailer {{ commit={}, human={:.0}%, ai={:.0}%, reviewer={}, ledger={} }}",
            &self.commit_sha[..std::cmp::min(8, self.commit_sha.len())],
            self.human_weight * 100.0,
            self.ai_weight * 100.0,
            self.hitl_signature.reviewer_id,
            self.revenue_split.ledger,
        )
    }
}

// ─── CLI Handlers ─────────────────────────────────────────────────────────────

/// Options parsed from `uws ip sign` arguments.
pub struct SignOptions {
    pub hitl_weight: f64,
    pub ai_weight: f64,
    pub reviewer_id: String,
    pub ledger: String,
    pub creator_pct: u8,
    pub description: String,
    pub dry_run: bool,
}

impl Default for SignOptions {
    fn default() -> Self {
        SignOptions {
            hitl_weight: 0.80,
            ai_weight: 0.20,
            reviewer_id: "unknown".to_string(),
            ledger: "github-sponsors".to_string(),
            creator_pct: 80,
            description: String::new(),
            dry_run: false,
        }
    }
}

/// Parse `--key=value` or `--key value` pairs from an arg slice.
fn parse_flag_value<'a>(args: &'a [String], flag: &str) -> Option<&'a str> {
    let prefix = format!("--{flag}=");
    for (i, arg) in args.iter().enumerate() {
        if let Some(val) = arg.strip_prefix(&prefix) {
            return Some(val);
        }
        if arg == &format!("--{flag}") {
            return args.get(i + 1).map(|s| s.as_str());
        }
    }
    None
}

/// Handle `uws ip sign [flags]`
///
/// Appends a cryptographic provenance trailer to the current HEAD commit by
/// writing a JSON record to stdout (and, when not `--dry-run`, to a git note).
///
/// # Flags
///   --hitl-weight=<f>    Human contribution fraction, default 0.80
///   --ai-weight=<f>      AI contribution fraction, default 0.20
///   --reviewer=<id>      Reviewer identifier, default git user.email
///   --ledger=<name>      Payout ledger, default "github-sponsors"
///   --creator-pct=<n>    Creator revenue %, default 80
///   --description=<str>  IP description
///   --dry-run            Print the trailer without writing it
pub fn handle_ip_sign(args: &[String]) -> Result<(), String> {
    let mut opts = SignOptions::default();

    if let Some(v) = parse_flag_value(args, "hitl-weight") {
        opts.hitl_weight = v
            .parse::<f64>()
            .map_err(|_| format!("--hitl-weight must be a decimal (e.g. 0.9), got: {v}"))?;
    }
    if let Some(v) = parse_flag_value(args, "ai-weight") {
        opts.ai_weight = v
            .parse::<f64>()
            .map_err(|_| format!("--ai-weight must be a decimal (e.g. 0.1), got: {v}"))?;
    }
    if let Some(v) = parse_flag_value(args, "reviewer") {
        opts.reviewer_id = v.to_string();
    }
    if let Some(v) = parse_flag_value(args, "ledger") {
        opts.ledger = v.to_string();
    }
    if let Some(v) = parse_flag_value(args, "creator-pct") {
        opts.creator_pct = v
            .parse::<u8>()
            .map_err(|_| format!("--creator-pct must be 0-100, got: {v}"))?;
    }
    if let Some(v) = parse_flag_value(args, "description") {
        opts.description = v.to_string();
    }
    if args.iter().any(|a| a == "--dry-run") {
        opts.dry_run = true;
    }

    // Default reviewer to git config user.email when not supplied.
    if opts.reviewer_id == "unknown" {
        if let Ok(output) = std::process::Command::new("git")
            .args(["config", "user.email"])
            .output()
        {
            let email = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if !email.is_empty() {
                opts.reviewer_id = email;
            }
        }
    }

    // Resolve HEAD commit SHA.
    let commit_sha = resolve_head_sha().unwrap_or_else(|| "HEAD".to_string());

    // Build the trailer.
    let trailer = ProvenanceTrailer::new(
        &commit_sha,
        &opts.description,
        opts.hitl_weight,
        opts.ai_weight,
        &opts.reviewer_id,
        opts.creator_pct,
        &opts.ledger,
        &opts.reviewer_id,
    )?;

    let json = trailer.to_json();

    if opts.dry_run {
        println!("{json}");
        return Ok(());
    }

    // Write as a git note on HEAD so it is permanently attached to the commit.
    let note_result = std::process::Command::new("git")
        .args(["notes", "add", "-m", &json])
        .status();

    match note_result {
        Ok(status) if status.success() => {
            println!("{json}");
            eprintln!(
                "✓ Provenance trailer appended to commit {} as a git note.",
                &commit_sha[..std::cmp::min(8, commit_sha.len())]
            );
        }
        _ => {
            // Git notes may fail outside of a git repo (e.g. in tests).
            // Still output the JSON so callers can pipe it.
            println!("{json}");
            eprintln!(
                "⚠ Could not write git note (is this inside a git repository?). \
                 Trailer printed to stdout."
            );
        }
    }

    Ok(())
}

/// Handle `uws ip monetize [flags]`
///
/// Stub for registering the current HEAD commit's IP with a decentralised
/// payout ledger.  Prints the registration payload and exits.
///
/// # Flags
///   --ledger=<name>   Target ledger, default "krakoa-free-bank"
///   --dry-run         Print payload without submitting
pub fn handle_ip_monetize(args: &[String]) -> Result<(), String> {
    let ledger = parse_flag_value(args, "ledger")
        .unwrap_or("krakoa-free-bank")
        .to_string();
    let dry_run = args.iter().any(|a| a == "--dry-run");

    let commit_sha = resolve_head_sha().unwrap_or_else(|| "HEAD".to_string());
    let timestamp = current_timestamp();

    // Attempt to read an existing provenance note for this commit.
    let existing_note = read_git_note(&commit_sha);

    let payload = format!(
        concat!(
            "{{",
            "\"action\":\"register_ip\",",
            "\"ledger\":\"{ledger}\",",
            "\"commit_sha\":\"{sha}\",",
            "\"timestamp\":\"{ts}\",",
            "\"provenance_trailer\":{pt},",
            "\"status\":\"stub — ledger integration pending\"",
            "}}"
        ),
        ledger = ledger,
        sha = commit_sha,
        ts = timestamp,
        pt = existing_note.unwrap_or_else(|| "null".to_string()),
    );

    if dry_run {
        println!("{payload}");
        return Ok(());
    }

    // TODO: Submit `payload` to the configured ledger endpoint.
    // For now this is a stub that prints the registration intent.
    println!("{payload}");
    eprintln!(
        "ℹ  Monetisation stub executed. \
         Connect a ledger endpoint via UWS_LEDGER_URL to enable live payouts."
    );

    Ok(())
}

/// Print usage information for `uws ip`.
pub fn print_ip_usage() {
    println!("uws ip — Regenerative IP & Provenance Engine");
    println!();
    println!("USAGE:");
    println!("    uws ip <SUBCOMMAND> [FLAGS]");
    println!();
    println!("SUBCOMMANDS:");
    println!("    sign        Append a cryptographic provenance trailer to HEAD");
    println!("    monetize    Register the IP with a decentralised payout ledger");
    println!();
    println!("FLAGS for `sign`:");
    println!("    --hitl-weight=<f>   Human contribution fraction (default: 0.80)");
    println!("    --ai-weight=<f>     AI contribution fraction   (default: 0.20)");
    println!("    --reviewer=<id>     Reviewer ID / email        (default: git user.email)");
    println!("    --ledger=<name>     Payout ledger name         (default: github-sponsors)");
    println!("    --creator-pct=<n>   Creator revenue share %    (default: 80)");
    println!("    --description=<s>   Human-readable IP description");
    println!("    --dry-run           Print trailer without writing git note");
    println!();
    println!("FLAGS for `monetize`:");
    println!("    --ledger=<name>     Target ledger              (default: krakoa-free-bank)");
    println!("    --dry-run           Print payload without submitting");
    println!();
    println!("EXAMPLES:");
    println!("    uws ip sign --hitl-weight=0.9 --ai-weight=0.1 --reviewer=alice@example.com");
    println!("    uws ip sign --dry-run");
    println!("    uws ip monetize --ledger=github-sponsors");
}

// ─── Private Helpers ──────────────────────────────────────────────────────────

/// Produce a deterministic canonical string for signing.
fn canonical_payload(
    commit_sha: &str,
    description: &str,
    human_weight: f64,
    ai_weight: f64,
    revenue_split: &RevenueSplit,
    reviewer_id: &str,
    timestamp: &str,
) -> String {
    format!(
        "{commit_sha}|{description}|{human_weight}|{ai_weight}|\
         {creator_id}|{creator_pct}|{ledger}|{reviewer_id}|{timestamp}",
        commit_sha = commit_sha,
        description = description,
        human_weight = human_weight,
        ai_weight = ai_weight,
        creator_id = revenue_split.creator_id,
        creator_pct = revenue_split.creator_pct,
        ledger = revenue_split.ledger,
        reviewer_id = reviewer_id,
        timestamp = timestamp,
    )
}

/// Escape a string for safe embedding as a JSON string value (including quotes).
///
/// Escapes: `\`, `"`, `\n`, `\r`, `\t`, and ASCII control characters (U+0000–U+001F).
fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                // Escape remaining control characters as \uXXXX
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Portable FNV-1a 256-bit signature (4 × 64-bit segments).
///
/// **Security note**: This is a portable, dependency-free implementation
/// suitable for non-adversarial integrity proofs.  It is NOT cryptographically
/// secure against a determined attacker.  Before deploying provenance trailers
/// in an adversarial context, replace this function with Ed25519 or ML-DSA
/// (FIPS 204 / Dilithium) signing.
fn portable_sign(input: &str) -> String {
    let bytes = input.as_bytes();

    let segment = |seed: u64| -> u64 {
        let mut h: u64 = 0xcbf29ce484222325u64.wrapping_add(seed);
        for &b in bytes {
            h ^= b as u64;
            h = h.wrapping_mul(0x100000001b3);
        }
        h
    };

    let h0 = segment(0);
    let h1 = segment(h0);
    let h2 = segment(h1);
    let h3 = segment(h2);
    format!("{h0:016x}{h1:016x}{h2:016x}{h3:016x}")
}

/// Resolve the SHA of the current HEAD commit via `git rev-parse HEAD`.
fn resolve_head_sha() -> Option<String> {
    std::process::Command::new("git")
        .args(["rev-parse", "HEAD"])
        .output()
        .ok()
        .and_then(|o| {
            if o.status.success() {
                let s = String::from_utf8_lossy(&o.stdout).trim().to_string();
                if s.is_empty() { None } else { Some(s) }
            } else {
                None
            }
        })
}

/// Read an existing git note for `commit_sha`, if any.
fn read_git_note(commit_sha: &str) -> Option<String> {
    std::process::Command::new("git")
        .args(["notes", "show", commit_sha])
        .output()
        .ok()
        .and_then(|o| {
            if o.status.success() {
                let s = String::from_utf8_lossy(&o.stdout).trim().to_string();
                if s.is_empty() { None } else { Some(s) }
            } else {
                None
            }
        })
}

/// ISO 8601 UTC timestamp (seconds since epoch, simplified).
fn current_timestamp() -> String {
    match SystemTime::now().duration_since(UNIX_EPOCH) {
        Ok(d) => format!("{}Z", d.as_secs()),
        Err(_) => "unknownZ".to_string(),
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn make_trailer(human: f64, ai: f64) -> Result<ProvenanceTrailer, String> {
        ProvenanceTrailer::new(
            "abc1234",
            "Test IP asset",
            human,
            ai,
            "alice@example.com",
            80,
            "github-sponsors",
            "alice@example.com",
        )
    }

    #[test]
    fn test_valid_trailer_created() {
        let t = make_trailer(0.8, 0.2).unwrap();
        assert_eq!(t.human_weight, 0.8);
        assert_eq!(t.ai_weight, 0.2);
        assert_eq!(t.revenue_split.creator_pct, 80);
        assert_eq!(t.revenue_split.ledger, "github-sponsors");
    }

    #[test]
    fn test_rejects_zero_human_weight() {
        let err = make_trailer(0.0, 1.0).unwrap_err();
        assert!(err.contains("human_weight"), "expected human_weight error, got: {err}");
    }

    #[test]
    fn test_rejects_mismatched_weights() {
        let err = make_trailer(0.5, 0.3).unwrap_err();
        assert!(err.contains("must equal 1.0"), "expected sum error, got: {err}");
    }

    #[test]
    fn test_signature_verifies() {
        let t = make_trailer(0.7, 0.3).unwrap();
        assert!(t.verify(), "signature should verify against its own payload");
    }

    #[test]
    fn test_to_json_contains_fields() {
        let t = make_trailer(0.6, 0.4).unwrap();
        let json = t.to_json();
        assert!(json.contains("\"schema_version\""));
        assert!(json.contains("\"commit_sha\""));
        assert!(json.contains("\"human_weight\""));
        assert!(json.contains("\"ai_weight\""));
        assert!(json.contains("\"hitl_signature\""));
    }

    #[test]
    fn test_display_format() {
        let t = make_trailer(0.9, 0.1).unwrap();
        let s = format!("{t}");
        assert!(s.contains("90%"), "display should show 90% human: {s}");
        assert!(s.contains("10%"), "display should show 10% ai: {s}");
    }

    #[test]
    fn test_parse_flag_value_equals_syntax() {
        let args: Vec<String> = vec!["--hitl-weight=0.75".to_string()];
        assert_eq!(parse_flag_value(&args, "hitl-weight"), Some("0.75"));
    }

    #[test]
    fn test_parse_flag_value_space_syntax() {
        let args: Vec<String> = vec!["--hitl-weight".to_string(), "0.75".to_string()];
        assert_eq!(parse_flag_value(&args, "hitl-weight"), Some("0.75"));
    }

    #[test]
    fn test_parse_flag_value_missing() {
        let args: Vec<String> = vec![];
        assert_eq!(parse_flag_value(&args, "hitl-weight"), None);
    }

    #[test]
    fn test_handle_ip_sign_dry_run() {
        let args: Vec<String> = vec![
            "--hitl-weight=0.8".to_string(),
            "--ai-weight=0.2".to_string(),
            "--reviewer=test@example.com".to_string(),
            "--dry-run".to_string(),
        ];
        // Should succeed without error.
        assert!(handle_ip_sign(&args).is_ok());
    }

    #[test]
    fn test_handle_ip_sign_bad_weight() {
        let args: Vec<String> = vec![
            "--hitl-weight=not-a-number".to_string(),
        ];
        assert!(handle_ip_sign(&args).is_err());
    }

    #[test]
    fn test_handle_ip_monetize_dry_run() {
        let args: Vec<String> = vec!["--dry-run".to_string()];
        assert!(handle_ip_monetize(&args).is_ok());
    }

    #[test]
    fn test_json_escape_special_chars() {
        assert_eq!(json_escape("hello"), "\"hello\"");
        assert_eq!(json_escape("say \"hi\""), "\"say \\\"hi\\\"\"");
        assert_eq!(json_escape("line1\nline2"), "\"line1\\nline2\"");
        assert_eq!(json_escape("back\\slash"), "\"back\\\\slash\"");
        assert_eq!(json_escape("tab\there"), "\"tab\\there\"");
    }

    #[test]
    fn test_to_json_escapes_description() {
        let t = ProvenanceTrailer::new(
            "abc1234",
            "Test with \"quotes\" and\nnewlines",
            0.8,
            0.2,
            "alice@example.com",
            80,
            "github-sponsors",
            "alice@example.com",
        )
        .unwrap();
        let json = t.to_json();
        // The description must be escaped in the JSON output.
        assert!(json.contains("\\\"quotes\\\""), "quotes should be escaped: {json}");
        assert!(json.contains("\\n"), "newline should be escaped: {json}");
    }

    #[test]
    fn test_portable_sign_deterministic() {
        let a = portable_sign("payload-abc");
        let b = portable_sign("payload-abc");
        assert_eq!(a, b);
        let c = portable_sign("payload-xyz");
        assert_ne!(a, c);
    }

    #[test]
    fn test_portable_sign_length() {
        let h = portable_sign("anything");
        assert_eq!(h.len(), 64);
    }
}
